### ISSUE TITLE
Random  crash in MQTTCFSocketEncoder.m (MQTT-Client version is 0.15.2)

### ISSUE THREAD

**Issue by Ramonfan** [novastone-media/MQTT-Client-Framework#526] opened 2019-04-19 11:55 UTC
<img width="932" alt="image" src="https://user-images.githubusercontent.com/8336766/56423097-1d470980-62dd-11e9-945b-df8b5007a288.png">

**Comment by jcavar** [comment] 2019-10-15 13:05
Thanks for your report, I will close as it is duplicate of another issue.

**Closed by jcavar** 2019-10-15 13:05 UTC
