### ISSUE TITLE
Conflicts class name Timer

### ISSUE THREAD

**Issue by RajaReddyIOS** [novastone-media/MQTT-Client-Framework#409] opened 2018-01-02 05:58 UTC
am recently updated pods.. on some where am using Timer Object (Foundation frame work) and on that class am using mqttClient also.. in mqttClient has Timer Class... my issue is getting conflicts (am using timer object (foundation frame work) it showing mqtt frame work)

**Comment by jcavar** [comment] 2018-01-02 08:52
Duplicate of #407

**Closed by jcavar** 2018-01-02 08:52 UTC
